import argparse
from pathlib import Path
from typing import Any
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling_core.types.doc import ImageRefMode
from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions, TableFormerMode, PictureDescriptionApiOptions, TableStructureOptions
from docling.backend.pypdfium2_backend import PyPdfiumDocumentBackend

# configuration for ollama vlm
OLLAMA_URL = "http://localhost:11434"
VLM_MODEL = "minicpm-v:8b"
# VLM_MODEL = "qwen3-vl:2b"
VLM_PROMPT = "Act as a senior financial analyst. Explain what you see in the image in one or two sentences. Focus on trends, tickers (only if you're sure) and do not mention anything that is not in the image. Be concise and accurate."

PAGE_BREAK_PLACEHOLDER = "<!-- page_break -->"
IMAGE_DESCRIPTION_START = "<image_description>"
IMAGE_DESCRIPTION_END = "</image_description>"

def create_picture_description_options() -> PictureDescriptionApiOptions:
    return PictureDescriptionApiOptions(
        url= f"{OLLAMA_URL}/v1/chat/completions",
        params= dict[str, Any](
            model= VLM_MODEL,
            think= False,
            seed= 72,
            max_completion_tokens= 256
        ),
        prompt= VLM_PROMPT,
        timeout=90
    )

def create_pdf_pipeline_options() -> PdfPipelineOptions:
    return PdfPipelineOptions(
        enable_remote_services=True,
        do_ocr=False,
        do_table_structure=True,
        generate_picture_images=True,
        do_picture_description=True,
        table_structure_options=TableStructureOptions(
            mode=TableFormerMode.ACCURATE,  # uses high-precision model
        ),
        picture_description_options=create_picture_description_options()
    )

def process_document(pdf_path: str):
    # initialize the converter with specific PDF options
    converter = DocumentConverter(
        format_options={
            InputFormat.PDF: PdfFormatOption(
                pipeline_options=create_pdf_pipeline_options(),
                backend=PyPdfiumDocumentBackend
            )
        }
    )

    # convert the PDF
    print(f"Processing: {pdf_path}...")
    result = converter.convert(pdf_path)
    doc = result.document

    # export to Markdown with image annotations
    content = doc.export_to_markdown(
        image_mode=ImageRefMode.PLACEHOLDER,
        image_placeholder="",
        page_break_placeholder=PAGE_BREAK_PLACEHOLDER,
        include_annotations=True,   # include the descriptions generated by the vlm
        mark_annotations=True
    )

    # clean up annotation tags for a cleaner look
    content = content.replace('<!--<annotation kind="description">-->', IMAGE_DESCRIPTION_START)
    content = content.replace('<!--<annotation>-->', IMAGE_DESCRIPTION_END)

    return content

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="A script to convert pdfs to markdown with VLM based image descriptions and tables")
    parser.add_argument("--input_file", required=True, help="The input pdf file name, with extension, located in data/pdfs folder")
    parser.add_argument("--output_file", help="The parsed output markdown filename, without extension, to be stored in data/others folder")
    args = parser.parse_args()
    if not args.output_file:
        args.output_file = Path(args.input_file).stem

    file_name = Path(args.input_file)
    md_content = process_document(f"../data/pdfs/{file_name}")
    Path(f"../data/others/{args.output_file}.md").write_text(md_content)